const API=location.hostname==='localhost'||location.hostname==='127.0.0.1'?'http://localhost:3000':'https://profile-platform.onrender.com';
const token=localStorage.getItem('token'); if(!token) location.href='login.html';
const headers={Authorization:`Bearer ${token}`,'Content-Type':'application/json'}; let page=1,count=0,limit=75,currentEmail=null,debounce; let mailboxRows=[];
const $=id=>document.getElementById(id); const esc=v=>String(v||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(path,opt={}){const r=await fetch(API+path,{...opt,headers:{...headers,...(opt.headers||{})}});if(r.status===401){localStorage.removeItem('token');location.href='login.html';return}const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||`Request failed (${r.status})`);return j}
function params(){const p=new URLSearchParams({page,limit});const q=$('searchInput').value.trim();if(q)p.set('q',q);p.set('source',$('sourceFilter').value);p.set('mailbox',$('mailboxFilter').value);p.set('type',$('typeFilter').value);p.set('store',$('storeFilter').value);p.set('linked',$('linkedFilter').value);return p}
function sourceLabel(value){return value==='aycd_import'?'AYCD imported direct':value==='aycd'?'AYCD bridge':value==='direct_imap'?'Direct IMAP':'Legacy source'}
function render(rows=[]){$('emailList').innerHTML=rows.length?rows.map(e=>`<article class="email-row"><div><b>${new Date(e.received_at).toLocaleDateString()}</b><div class="muted">${new Date(e.received_at).toLocaleTimeString()}</div><div class="muted">${esc(e.mailbox_email||'AYCD unified')}</div><div class="muted">${sourceLabel(e.source_type)}</div></div><div><div class="email-subject">${esc(e.subject||'(no subject)')}</div><div class="muted">From: ${esc(e.from_text||'Unknown sender')}</div><div class="snippet">${esc(e.snippet||'')}</div><div class="row-actions"><button class="btn" onclick="openLink('${e.id}','${esc((e.subject||'').replace(/'/g,'&#39;'))}')">${e.linked_order_id?'Relink':'Link to order'}</button>${e.linked_order_id?`<button class="btn" onclick="unlinkEmail('${e.id}')">Unlink</button>`:''}</div></div><div><span class="pill">${esc(e.store)}</span><div style="margin-top:7px"><span class="pill ${e.is_order_related?'pill-green':'pill-gray'}">${esc(e.email_type)}</span></div></div><div><b>${esc(e.order_number||'No order #')}</b><div class="muted">${e.linked_order_id?'Linked':'Not linked'}</div>${e.keep_forever?'<div class="muted">Retained</div>':'<div class="muted">Temporary</div>'}</div></article>`).join(''):'<div style="padding:28px;text-align:center" class="muted">No emails match this view.</div>'}
function visibleMailboxRows(){const source=$('sourceFilter').value;return mailboxRows.filter(r=>!r.hidden&&(source==='all'||r.source_type===source))}
function rebuildMailboxFilter(){const current=$('mailboxFilter').value;const rows=visibleMailboxRows();$('mailboxFilter').innerHTML='<option value="all">All email accounts</option>'+rows.map(r=>`<option value="${esc(r.mailbox_email)}">${sourceLabel(r.source_type)} • ${esc(r.mailbox_email)} (${Number(r.count||0)})</option>`).join('');if([...$('mailboxFilter').options].some(o=>o.value===current))$('mailboxFilter').value=current;else $('mailboxFilter').value='all'}
function renderMailboxManager(){const grouped={aycd_import:[],aycd:[],direct_imap:[],legacy:[]};for(const row of mailboxRows)(grouped[row.source_type]||grouped.legacy).push(row);const section=(title,rows)=>`<div><b>${title}</b>${rows.map(r=>`<div class="mailbox-item"><label><input type="checkbox" ${r.hidden?'checked':''} onchange="toggleMailbox('${esc(r.mailbox_email)}',this.checked)"><span>${esc(r.mailbox_email)}</span></label><small>${Number(r.count||0)} emails</small></div>`).join('')||'<div class="muted" style="padding:8px">No accounts found.</div>'}</div>`;$('mailboxManager').innerHTML=section('AYCD imported direct accounts',grouped.aycd_import)+section('AYCD bridge accounts',grouped.aycd)+section('Direct IMAP accounts',grouped.direct_imap)+(grouped.legacy.length?section('Older indexed emails (source not recorded)',grouped.legacy):'')}
async function loadMailboxes(){try{const j=await api('/admin/email-center/mailboxes');mailboxRows=j.mailboxes||[];renderMailboxManager();rebuildMailboxFilter()}catch(e){$('mailboxManager').innerHTML=`<div class="muted">${esc(e.message)}</div>`}}
window.toggleMailbox=async(email,hidden)=>{await api('/admin/email-center/mailbox-visibility',{method:'POST',body:JSON.stringify({mailbox_email:email,hidden})});const row=mailboxRows.find(r=>r.mailbox_email===email);if(row)row.hidden=hidden;renderMailboxManager();rebuildMailboxFilter();page=1;load()};
async function load(){try{$('statusText').textContent='Loading emails…';const j=await api('/admin/email-center?'+params());count=j.count||0;render(j.emails||[]);const s=j.summary||{};$('totalCount').textContent=s.total||0;$('keptCount').textContent=s.kept||0;$('linkedCount').textContent=s.linked||0;$('confirmedCount').textContent=s.confirmed||0;$('shippingCount').textContent=(s.shipped||0)+(s.delivered||0);const pages=Math.max(1,Math.ceil(count/limit));$('pageText').textContent=`Page ${page} of ${pages} • ${count.toLocaleString()} matching emails`;$('prevBtn').disabled=page<=1;$('nextBtn').disabled=page>=pages;$('statusText').textContent='';}catch(e){$('statusText').textContent=e.message}}
window.openLink=async(id,title)=>{currentEmail=id;$('linkEmailTitle').textContent=title;$('linkModal').hidden=false;$('orderSearch').value='';await searchOrders()};
window.unlinkEmail=async id=>{if(!confirm('Unlink this email from its order?'))return;await api(`/admin/email-center/${id}/unlink`,{method:'POST',body:'{}'});load()};
async function searchOrders(){const q=$('orderSearch').value.trim();const j=await api('/admin/email-center/orders?q='+encodeURIComponent(q));$('orderResults').innerHTML=(j.orders||[]).map(o=>`<div class="order-option" onclick="linkOrder('${o.id}')"><b>${esc(o.store).toUpperCase()} · ${esc(o.order_number)}</b><div>${esc(o.product_summary||'')}</div><div class="muted">${esc(o.status)} · ${esc(o.source_email||'')}</div></div>`).join('')||'<div class="muted">No orders found.</div>'}
window.linkOrder=async orderId=>{await api(`/admin/email-center/${currentEmail}/link`,{method:'POST',body:JSON.stringify({order_id:orderId})});$('linkModal').hidden=true;load()};
$('searchBtn').onclick=()=>{page=1;load()};$('searchInput').oninput=()=>{clearTimeout(debounce);debounce=setTimeout(()=>{page=1;load()},450)};$('typeFilter').onchange=$('storeFilter').onchange=$('linkedFilter').onchange=$('mailboxFilter').onchange=()=>{page=1;load()};$('sourceFilter').onchange=()=>{rebuildMailboxFilter();page=1;load()};$('prevBtn').onclick=()=>{if(page>1){page--;load()}};$('nextBtn').onclick=()=>{page++;load()};$('closeModal').onclick=()=>{$('linkModal').hidden=true};$('orderSearch').oninput=()=>{clearTimeout(debounce);debounce=setTimeout(searchOrders,350)};
$('cleanupBtn').onclick=async()=>{const days=prompt('Delete unlinked, non-order email metadata older than how many days? Enter 0 to delete all temporary metadata now.','30');if(days===null)return;if(!confirm('Order-related and linked emails will be kept. Continue?'))return;const j=await api('/admin/email-center/cleanup',{method:'POST',body:JSON.stringify({older_than_days:Number(days)})});alert(`Deleted ${j.deleted||0} temporary email records.`);page=1;load();loadMailboxes()};
$('backfillBtn').onclick=async()=>{const j=await api('/admin/email-center/backfill-order-events',{method:'POST',body:'{}'});alert(`Imported ${j.saved||0} previously processed order email events.`);load();loadMailboxes()};
let importedAccounts=[];
function importedStatusClass(status){return status==='connected'?'status-ok':status==='error'?'status-bad':status==='placeholder'?'status-warn':''}
function fmtDate(v){return v?new Date(v).toLocaleString():'—'}
function renderImportedAccounts(summary={}){
  $('importedSummary').innerHTML=`<span>${Number(summary.total||0)} imported</span><span>${Number(summary.enabled||0)} enabled</span><span>${Number(summary.matched||0)} profile matched</span><span>${Number(summary.ambiguous||0)} ambiguous</span>`;
  $('importedAccountsBody').innerHTML=importedAccounts.length?importedAccounts.map(a=>`<tr><td><b>${esc(a.email)}</b><div class="muted">${esc(a.category||'')}</div></td><td>${esc(a.provider||'')}</td><td>${esc(a.auth_method||'')}</td><td>${esc(a.match_status||'unmatched')}</td><td class="${importedStatusClass(a.status)}"><b>${esc(a.status||'')}</b>${a.last_error?`<div class="muted" title="${esc(a.last_error)}">${esc(String(a.last_error).slice(0,100))}</div>`:''}</td><td>${fmtDate(a.last_scan_at||a.last_test_at)}</td><td><button class="btn" onclick="testImportedAccount('${a.id}')">Test</button><button class="btn" onclick="rescanImportedHistory('${a.id}','${esc(a.email)}')">Rescan history</button><button class="btn" onclick="toggleImportedAccount('${a.id}',${a.is_enabled?'false':'true'})">${a.is_enabled?'Disable':'Enable'}</button></td></tr>`).join(''):'<tr><td colspan="7" class="muted">No AYCD CSV accounts imported yet.</td></tr>';
}
async function loadImportedAccounts(){try{const j=await api('/admin/email-center/imported-accounts');importedAccounts=j.accounts||[];renderImportedAccounts(j.summary||{});$('importedStatus').textContent=''}catch(e){$('importedStatus').textContent=e.message}}
$('chooseAycdCsvBtn').onclick=()=>$('aycdCsvFile').click();
$('aycdCsvFile').onchange=async()=>{const file=$('aycdCsvFile').files?.[0];if(!file)return;try{$('importedStatus').textContent=`Reading ${file.name}…`;const csv=await file.text();$('importedStatus').textContent='Encrypting and importing mailbox credentials…';const j=await api('/admin/email-center/import-aycd-accounts',{method:'POST',body:JSON.stringify({csv})});$('importedStatus').textContent=`${j.message} Matched: ${j.matched||0}; placeholders/unsupported: ${j.placeholders||0}.`;await loadImportedAccounts();await loadMailboxes();}catch(e){$('importedStatus').textContent=e.message}finally{$('aycdCsvFile').value=''}};
async function pollDirectScan(){
  const deadline=Date.now()+30*60*1000;
  while(Date.now()<deadline){
    const j=await api('/orders/scan-progress'); const job=j.job;
    if(!job){$('importedStatus').textContent='No active direct mailbox scan.';return}
    if(job.status==='running'){
      const accountPart=job.accountTotal?`${job.accountIndex||0}/${job.accountTotal} mailboxes`:'mailboxes';
      const msgPart=job.total?` · ${job.checked||0}/${job.total} messages`:'';
      $('importedStatus').textContent=`Direct scan ${job.percent||0}% — ${job.email||'preparing'} — ${accountPart}${msgPart}`;
      await new Promise(r=>setTimeout(r,1200)); continue;
    }
    $('importedStatus').textContent=job.status==='complete'?'Direct mailbox scan complete.':`Direct mailbox scan ${job.status}: ${job.error||job.message||''}`;
    await Promise.all([loadImportedAccounts(),loadMailboxes(),load()]); return;
  }
  $('importedStatus').textContent='Direct mailbox scan is still running in the background. You can leave this page safely.';
}
$('scanImportedBtn').onclick=async()=>{try{$('importedStatus').textContent='Starting direct mailbox scan…';await api('/orders/scan/start',{method:'POST',body:'{}'});pollDirectScan().catch(e=>$('importedStatus').textContent=e.message)}catch(e){$('importedStatus').textContent=e.message}};
$('rematchImportedBtn').onclick=async()=>{try{$('importedStatus').textContent='Rechecking imported mailbox ownership against profile login emails…';const j=await api('/admin/email-center/imported-accounts/rematch',{method:'POST',body:'{}'});$('importedStatus').textContent=`Rematch complete: ${j.matched||0} matched, ${j.ambiguous||0} ambiguous, ${j.unmatched||0} unmatched.`;await loadImportedAccounts()}catch(e){$('importedStatus').textContent=e.message}};
$('refreshImportedBtn').onclick=()=>loadImportedAccounts();
window.testImportedAccount=async id=>{try{$('importedStatus').textContent='Testing direct mailbox connection…';const j=await api(`/admin/email-center/imported-accounts/${id}/test`,{method:'POST',body:'{}'});$('importedStatus').textContent=`Connected to ${j.email}. Inbox currently exposes ${j.messages} messages.`;await loadImportedAccounts()}catch(e){$('importedStatus').textContent=e.message;await loadImportedAccounts()}};
window.toggleImportedAccount=async(id,is_enabled)=>{try{await api(`/admin/email-center/imported-accounts/${id}`,{method:'PATCH',body:JSON.stringify({is_enabled})});await loadImportedAccounts()}catch(e){$('importedStatus').textContent=e.message}};
Promise.all([loadMailboxes(),load(),loadImportedAccounts()]);

window.rescanImportedHistory=async(id,email)=>{if(!confirm(`Reset the saved IMAP checkpoint for ${email} and rescan its available history? This only affects this mailbox.`))return;try{$('importedStatus').textContent=`Resetting ${email} history checkpoint…`;const j=await api(`/admin/email-center/imported-accounts/${id}/rescan-history`,{method:'POST',body:'{}'});$('importedStatus').textContent=j.message||`History rescan started for ${email}.`;setTimeout(()=>loadImportedAccounts(),5000)}catch(e){$('importedStatus').textContent=e.message}};
