const API=location.hostname==='localhost'||location.hostname==='127.0.0.1'?'http://localhost:3000':'https://profile-platform.onrender.com';const token=localStorage.getItem('token');if(!token)location.href='login.html';const H={Authorization:`Bearer ${token}`,'Content-Type':'application/json'};let items=[],activeItem=null,config={};
function logout(){localStorage.removeItem('token');location.href='login.html'}function m(n){return `$${Number(n||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}`}function e(v){return String(v||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}async function api(p,o={}){const r=await fetch(API+p,{...o,headers:{...H,...(o.headers||{})}});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'Request failed');return j}
async function load(){const [j,c,h,a]=await Promise.all([api('/investment'),api('/market-value/config'),api('/market-value/history'),api('/market-value/alerts')]);items=j.items||[];config=c.providers||{};const s=j.summary||{};purchaseTotal.textContent=m(s.purchase);creditTotal.textContent=m(s.credits);investedTotal.textContent=m(s.invested);marketTotal.textContent=m(s.market);gainTotal.textContent=m(s.gain);gainTotal.className=s.gain>=0?'gain-pos':'gain-neg';roiTotal.textContent=`${Number(s.roi||0).toFixed(1)}% ROI`;renderProviders();renderFilters();render();drawHistory(h.history||[]);renderAlerts(a.alerts||[])}
function renderProviders(){const labels={tcgplayer:'TCGplayer',ebay:'eBay',stockx:'StockX',tradepost:'Tradepost',pricecharting:'PriceCharting',cardmarket:'Cardmarket'};providerList.innerHTML=Object.entries(labels).map(([k,v])=>`<div class="provider"><span>${v}</span><b class="${config[k]?'on':'off'}">${config[k]?'Automatic':'Search / manual'}</b></div>`).join('')}
function renderFilters(){const current=categoryFilter.value;const cats=[...new Set(items.map(x=>x.category).filter(Boolean))].sort();categoryFilter.innerHTML='<option value="">All categories</option>'+cats.map(x=>`<option>${e(x)}</option>`).join('');categoryFilter.value=current}
function render(){const q=searchBox.value.toLowerCase(),cat=categoryFilter.value;const rows=items.filter(i=>(!q||`${i.product_name} ${i.store} ${i.order_number||''}`.toLowerCase().includes(q))&&(!cat||i.category===cat));investmentList.innerHTML=rows.length?rows.map(i=>{const qty=Number(i.quantity||1),invested=Number(i.purchase_price||0)+Number(i.credits_value||0),market=Number(i.market_price||0)*qty,gain=market-invested;return `<div class="product-row"><img src="${e(i.image_url||'')}" onerror="this.style.visibility='hidden'"><div><b>${e(i.product_name)}</b><div class="subtle-text">${e(i.store||'')} ${i.order_number?'· '+e(i.order_number):''}</div><span class="source-pill">${e(i.category||'uncategorized')}</span><span class="source-pill">${e(i.condition||'sealed')}</span><span class="source-pill">${e(i.market_source||'unpriced')}</span></div><label>Qty<input data-id="${i.id}" data-k="quantity" type="number" min="1" value="${qty}"></label><label>Purchase<input data-id="${i.id}" data-k="purchase_price" type="number" step=".01" value="${i.purchase_price||0}"></label><label>Credits<input data-id="${i.id}" data-k="credits_value" type="number" step=".01" value="${i.credits_value||0}"></label><div><b>${m(market)}</b><div class="${gain>=0?'gain-pos':'gain-neg'}">${gain>=0?'+':''}${m(gain)}</div><small>${i.market_updated_at?'Updated '+new Date(i.market_updated_at).toLocaleDateString():'Not priced'}</small></div><div><button class="btn" onclick="saveItem('${i.id}')">Save</button><button class="btn" onclick="openSources('${i.id}')">Sources</button><button class="btn" onclick="newAlert('${i.id}')">Alert</button><button class="btn btn-danger" onclick="delItem('${i.id}')">Delete</button></div></div>`}).join(''):'<div class="empty">No matching products.</div>'}
async function saveItem(id){const patch={};document.querySelectorAll(`[data-id="${id}"]`).forEach(x=>patch[x.dataset.k]=x.value===''?null:Number(x.value));await api('/investment/'+id,{method:'PATCH',body:JSON.stringify(patch)});await load()}async function delItem(id){if(confirm('Delete this investment item?')){await api('/investment/'+id,{method:'DELETE'});await load()}}
addProduct.onclick=async()=>{try{await api('/investment',{method:'POST',body:JSON.stringify({product_name:pName.value,store:pStore.value,category:pCategory.value,upc:pUpc.value,condition:pCondition.value,quantity:pQty.value,purchase_price:pPurchase.value,credits_value:pCredits.value,market_price:pMarket.value,tcgplayer_product_id:pTcgId.value||null,tcgplayer_sku:pTcgSku.value||null})});document.querySelectorAll('.product-form input').forEach(x=>x.value='');pQty.value=1;await load()}catch(err){valueMessage.textContent=err.message}};
refreshAll.onclick=async()=>{refreshAll.disabled=true;valueMessage.textContent='Comparing available marketplaces...';try{const j=await api('/market-value/refresh',{method:'POST'});valueMessage.textContent=`Updated ${j.updated} products from configured sources.`;await load()}catch(err){valueMessage.textContent=err.message}finally{refreshAll.disabled=false}};
searchBox.oninput=render;categoryFilter.onchange=render;
async function openSources(id){activeItem=id;const j=await api('/market-value/sources/'+id);sourceTitle.textContent=j.item.product_name;sourceLinks.innerHTML=Object.entries(j.links||{}).map(([k,v])=>`<a class="btn" target="_blank" rel="noopener" href="${e(v)}">Search ${e(k)}</a>`).join('');sourceList.innerHTML=(j.observations||[]).map(x=>`<div class="source-row"><b>${e(x.source)}</b><div>${e(x.title||'')}<br><small>${new Date(x.observed_at).toLocaleString()}</small></div><div><b>${m(x.price)}</b>${x.listing_url?`<br><a target="_blank" href="${e(x.listing_url)}">Open</a>`:''}</div></div>`).join('')||'<div class="empty">No observations yet. Use a search button, then add the matching price below.</div>';sourceDialog.showModal()}
addObservation.onclick=async()=>{await api('/market-value/observations',{method:'POST',body:JSON.stringify({investment_product_id:activeItem,source:obsSource.value,price:obsPrice.value,listing_url:obsUrl.value})});obsPrice.value='';obsUrl.value='';await openSources(activeItem);await load()};
async function newAlert(id){const item=items.find(x=>x.id===id);const direction=confirm('Click OK for an ABOVE-price alert. Click Cancel for a BELOW-price alert.')?'above':'below';const target=prompt(`Alert when ${item.product_name} is ${direction} what price?`,item.market_price||'');if(!target)return;await api('/market-value/alerts',{method:'POST',body:JSON.stringify({investment_product_id:id,direction,target_price:target})});await load()}
function renderAlerts(list){alerts.innerHTML=list.length?list.map(a=>`<div class="alert-row"><span><b>${e(a.investment_products?.product_name||'Product')}</b><br><small>${a.direction} ${m(a.target_price)} ${a.triggered_at?'· Triggered':'· Active'}</small></span><button class="btn btn-danger" onclick="deleteAlert('${a.id}')">Delete</button></div>`).join(''):'<p class="subtle-text">No price alerts yet.</p>'}async function deleteAlert(id){await api('/market-value/alerts/'+id,{method:'DELETE'});await load()}
function drawHistory(history){const c=portfolioChart,ctx=c.getContext('2d'),dpr=devicePixelRatio||1,w=c.clientWidth||800,h=c.clientHeight||260;c.width=w*dpr;c.height=h*dpr;ctx.scale(dpr,dpr);ctx.clearRect(0,0,w,h);ctx.strokeStyle='#cbd5e1';ctx.beginPath();ctx.moveTo(42,10);ctx.lineTo(42,h-30);ctx.lineTo(w-10,h-30);ctx.stroke();if(!history.length){ctx.fillStyle='#64748b';ctx.fillText('Portfolio snapshots appear after pricing refreshes.',60,80);return}const vals=history.map(x=>Number(x.market_value||0)),max=Math.max(...vals,1),min=Math.min(...vals,0),range=Math.max(1,max-min);ctx.strokeStyle='#2563eb';ctx.lineWidth=3;ctx.beginPath();history.forEach((x,i)=>{const px=42+(w-58)*(i/Math.max(1,history.length-1)),py=10+(h-45)*(1-(Number(x.market_value)-min)/range);i?ctx.lineTo(px,py):ctx.moveTo(px,py)});ctx.stroke();ctx.fillStyle='#0f172a';ctx.fillText(m(max),4,18);ctx.fillText(m(min),4,h-30)}
window.addEventListener('resize',()=>api('/market-value/history').then(j=>drawHistory(j.history||[])));load().catch(err=>valueMessage.textContent=err.message);
