const API=location.hostname==='localhost'||location.hostname==='127.0.0.1'?'http://localhost:3000':'https://profile-platform.onrender.com';
const token=localStorage.getItem('token');
const AYCD_HELPER='http://127.0.0.1:43821'; if(!token) location.href='login.html';
const headers={'Authorization':`Bearer ${token}`,'Content-Type':'application/json'}; let allOrders=[];
function logout(){localStorage.removeItem('token');location.href='login.html'}
function money(n){return `$${Number(n||0).toFixed(2)}`}
function esc(v){return String(v||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function initYears(){const s=document.getElementById('yearFilter'),y=new Date().getFullYear();s.innerHTML='<option value="">All years</option>';for(let i=y;i>=y-7;i--)s.innerHTML+=`<option value="${i}">${i}</option>`}
async function api(path,opt={}){const r=await fetch(API+path,{...opt,headers:{...headers,...(opt.headers||{})}});if(r.status===401){logout();return}const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||`Request failed (${r.status})`);return j}
function renderAccounts(accounts=[]){const el=document.getElementById('scanAccounts');el.innerHTML=accounts.length?`<div class="connected-summary"><b>${accounts.length} connected IMAP account${accounts.length===1?'':'s'}</b></div>`+accounts.map(a=>`<div class="scan-account"><b>✓ ${esc(a.email)}</b> · ${esc(a.provider||'IMAP')} · ${a.last_success_at?'Last successful scan '+new Date(a.last_success_at).toLocaleString():'Saved in profile — not scanned yet'}${a.last_error?`<div class="error-text">${esc(a.last_error)}</div>`:''}</div>`).join(''):'<p class="subtle-text">No supported IMAP/app password was found in this user’s saved profiles.</p>'}
function applyOrders(orders=[],summary={}){allOrders=orders;render();countAll.textContent=allOrders.length;countActive.textContent=(summary.confirmed||0)+(summary.processing||0);countSuccess.textContent=(summary.shipped||0)+(summary.delivered||0);countCanceled.textContent=(summary.canceled||0)+(summary.refunded||0);successRate.textContent=`${Number(summary.success_rate||0).toFixed(1)}%`}
async function bootstrap(attempt=1){scanMessage.textContent=attempt===1?'Loading connected mailboxes and saved orders…':`Render is waking up. Retrying page load (${attempt}/4)…`;try{const j=await api('/orders/bootstrap');renderAccounts(j.accounts||[]);applyOrders(j.orders||[],j.summary||{});scanMessage.textContent=`Loaded ${j.connected_count||0} connected email account${Number(j.connected_count||0)===1?'':'s'} and ${Number((j.orders||[]).length)} saved platform order${Number((j.orders||[]).length)===1?'':'s'}. Scan Email Now only checks for new status emails.`;if(j.is_super_admin){aycdPanel.hidden=false;checkAycdHelper()}else if(window.aycdPanel){aycdPanel.hidden=true}return j}catch(error){if(attempt<4){await new Promise(resolve=>setTimeout(resolve,attempt*1500));return bootstrap(attempt+1)}throw error}}
async function loadStatus(){const j=await api('/orders/scan-status');renderAccounts(j.accounts||[])}
async function loadOrders(){const qs=new URLSearchParams();if(statusFilter.value)qs.set('status',statusFilter.value);if(yearFilter.value)qs.set('year',yearFilter.value);const j=await api('/orders/tracked?'+qs);applyOrders(j.orders||[],j.summary||{})}
function render(){const q=searchOrders.value.toLowerCase();const rows=allOrders.filter(o=>`${o.store} ${o.order_number} ${o.product_summary}`.toLowerCase().includes(q));ordersList.innerHTML=rows.length?rows.map(o=>`<article class="order-card"><div class="order-head"><div><span class="status-pill status-${esc(o.status)}">${esc(o.status)}</span><h3>${esc(o.store).toUpperCase()} · ${esc(o.order_number)}</h3><p>${esc(o.product_summary||'Product details will improve as receipt emails are parsed.')}</p></div><strong>${money(o.total)}</strong></div><div class="order-meta"><div><small>Order date</small><br><b>${o.order_date?new Date(o.order_date).toLocaleDateString():'—'}</b></div><div><small>Tracking</small><br><b>${esc(o.tracking_number||'—')}</b></div><div><small>Credits spent</small><br><b>${money(o.credits_spent)}</b></div><div><small>Last update</small><br><b>${o.last_status_at?new Date(o.last_status_at).toLocaleString():'—'}</b></div></div><div class="order-actions"><a class="btn" target="_blank" href="${API}/orders/receipt/${o.id}?token=${encodeURIComponent(token)}" onclick="event.preventDefault();openReceipt('${o.id}')">View / Print Receipt</a><button class="btn" onclick="editOrder('${o.id}')">Edit</button><button class="btn btn-danger" onclick="deleteOrder('${o.id}')">Delete</button></div></article>`).join(''):'<section class="panel"><p>No tracked orders match this view yet.</p></section>'}
async function openReceipt(id){const r=await fetch(`${API}/orders/receipt/${id}`,{headers:{Authorization:`Bearer ${token}`}});if(!r.ok){alert('Receipt could not be opened');return}const html=await r.text();const w=window.open('','_blank');w.document.open();w.document.write(html);w.document.close();}
async function editOrder(id){const o=allOrders.find(x=>x.id===id);const status=prompt('Status: confirmed, processing, shipped, delivered, canceled, refunded',o.status);if(!status)return;const credits=prompt('Credits spent for this order',o.credits_spent||0);await api('/orders/tracked/'+id,{method:'PATCH',body:JSON.stringify({status,credits_spent:Number(credits||0)})});loadOrders()}
async function deleteOrder(id){if(!confirm('Delete this tracked order and its stored receipt?'))return;await api('/orders/tracked/'+id,{method:'DELETE'});loadOrders()}
scanNow.onclick=async()=>{scanNow.disabled=true;scanMessage.textContent='Scanning connected inboxes. Large first scans can take a few minutes...';try{const j=await api('/orders/scan',{method:'POST'});scanMessage.textContent=`Scan complete: ${j.accounts||0} connected email account${Number(j.accounts||0)===1?'':'s'} checked.`;await bootstrap()}catch(e){scanMessage.textContent=e.message}finally{scanNow.disabled=false}};
async function helperApi(path,opt={}){const r=await fetch(AYCD_HELPER+path,{...opt,headers:{'Content-Type':'application/json',...(opt.headers||{})}});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||`Local helper request failed (${r.status})`);return j}
function aycdSettings(){return {host:aycdHost.value.trim()||'127.0.0.1',port:Number(aycdPort.value||43283),username:aycdUsername.value.trim()||'inbox@aycd.me',password:aycdPassword.value,secure:aycdSecure.checked,lookbackDays:Number(aycdLookback.value||30)}}
async function checkAycdHelper(){try{const j=await helperApi('/health');aycdBridgeStatus.textContent='Local helper running';aycdBridgeStatus.className='status-pill status-confirmed';if(j.configured){aycdHost.value=j.host||'127.0.0.1';aycdPort.value=j.port||43283;aycdUsername.value=j.username||'inbox@aycd.me';aycdSecure.checked=!!j.secure;aycdLookback.value=j.lookbackDays||30;aycdMessage.textContent='Local helper is ready. AYCD Inbox must remain open while testing or scanning.'}else aycdMessage.textContent='Local helper is running. Enter the AYCD IMAP password and save the connection.'}catch(e){aycdBridgeStatus.textContent='Local helper offline';aycdBridgeStatus.className='status-pill status-canceled';aycdMessage.textContent='Start local-aycd-bridge/start-aycd-bridge.bat on this laptop, then reload this page.'}}
if(window.saveAycd)saveAycd.onclick=async()=>{saveAycd.disabled=true;try{const j=await helperApi('/configure',{method:'POST',body:JSON.stringify(aycdSettings())});aycdPassword.value='';aycdMessage.textContent='AYCD Unified Inbox settings were saved locally on this laptop.';await checkAycdHelper()}catch(e){aycdMessage.textContent=e.message}finally{saveAycd.disabled=false}};
if(window.testAycd)testAycd.onclick=async()=>{testAycd.disabled=true;aycdMessage.textContent='Testing AYCD Unified Inbox on this laptop…';try{const j=await helperApi('/test',{method:'POST',body:JSON.stringify(aycdSettings())});aycdMessage.textContent=`Connected to AYCD Unified Inbox. ${Number(j.messages||0).toLocaleString()} messages are currently exposed in ${j.mailbox||'INBOX'}.`;}catch(e){aycdMessage.textContent=e.message}finally{testAycd.disabled=false}};
if(window.scanAycd)scanAycd.onclick=async()=>{scanAycd.disabled=true;aycdMessage.textContent='Scanning AYCD Unified Inbox and matching only orders recorded by this website…';try{const j=await helperApi('/scan',{method:'POST',body:JSON.stringify({settings:aycdSettings(),apiBase:API,token})});aycdMessage.textContent=`AYCD scan complete: ${j.checked||0} messages checked, ${j.matched||0} platform order updates found, ${j.ignored||0} unrelated messages ignored.`;await bootstrap()}catch(e){aycdMessage.textContent=e.message}finally{scanAycd.disabled=false}};
printYear.onclick=async()=>{const y=yearFilter.value||new Date().getFullYear();const r=await fetch(`${API}/orders/tax-export?year=${y}`,{headers:{Authorization:`Bearer ${token}`}});if(!r.ok){alert('Annual receipt archive could not be opened');return}const html=await r.text();const w=window.open('','_blank');w.document.open();w.document.write(html);w.document.close();};refreshOrders.onclick=bootstrap;statusFilter.onchange=loadOrders;yearFilter.onchange=loadOrders;searchOrders.oninput=render;
initYears();bootstrap().catch(e=>{scanMessage.textContent=`Page load failed after retries: ${e.message}`;countAll.textContent='—';countActive.textContent='—';countSuccess.textContent='—';countCanceled.textContent='—';successRate.textContent='—';ordersList.innerHTML='<section class="panel"><p>Unable to load saved orders. Use Refresh after the backend finishes waking up.</p></section>'});
