const API=location.hostname==='localhost'||location.hostname==='127.0.0.1'?'http://localhost:3000':'https://profile-platform.onrender.com';
const token=localStorage.getItem('token'); if(!token) location.href='login.html';
const headers={'Authorization':`Bearer ${token}`,'Content-Type':'application/json'}; let allOrders=[];
function logout(){localStorage.removeItem('token');location.href='login.html'}
function money(n){return `$${Number(n||0).toFixed(2)}`}
function esc(v){return String(v||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function initYears(){const s=document.getElementById('yearFilter'),y=new Date().getFullYear();s.innerHTML='<option value="">All years</option>';for(let i=y;i>=y-7;i--)s.innerHTML+=`<option value="${i}">${i}</option>`}
async function api(path,opt={}){const r=await fetch(API+path,{...opt,headers:{...headers,...(opt.headers||{})}});if(r.status===401){logout();return}const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||`Request failed (${r.status})`);return j}
function renderAccounts(accounts=[]){const el=document.getElementById('scanAccounts');el.innerHTML=accounts.length?`<div class="connected-summary"><b>${accounts.length} connected IMAP account${accounts.length===1?'':'s'}</b></div>`+accounts.map(a=>`<div class="scan-account"><b>✓ ${esc(a.email)}</b> · ${esc(a.provider||'IMAP')} · ${a.last_success_at?'Last successful scan '+new Date(a.last_success_at).toLocaleString():'Connected — not scanned yet'}${a.last_error?`<div class="error-text">${esc(a.last_error)}</div>`:''}</div>`).join(''):'<p class="subtle-text">No saved IMAP account is linked to this user. Open a profile, save the mailbox app password, and click Test IMAP Connection.</p>'}
function applyOrders(orders=[],summary={}){allOrders=orders;render();countAll.textContent=allOrders.length;countActive.textContent=(summary.confirmed||0)+(summary.processing||0);countSuccess.textContent=(summary.shipped||0)+(summary.delivered||0);countCanceled.textContent=(summary.canceled||0)+(summary.refunded||0);successRate.textContent=`${Number(summary.success_rate||0).toFixed(1)}%`}
async function bootstrap(){scanMessage.textContent='Loading connected mailboxes and saved orders…';const j=await api('/orders/bootstrap');renderAccounts(j.accounts||[]);applyOrders(j.orders||[],j.summary||{});scanMessage.textContent=`Loaded ${j.connected_count||0} connected email account${Number(j.connected_count||0)===1?'':'s'} and ${Number((j.orders||[]).length)} saved platform order${Number((j.orders||[]).length)===1?'':'s'}.`;if(j.aycd?.configured){aycdPanel.hidden=false;aycdMessage.textContent='AYCD Inbox is configured and ready for Super Admin bulk scans.'}}
async function loadStatus(){const j=await api('/orders/scan-status');renderAccounts(j.accounts||[])}
async function loadOrders(){const qs=new URLSearchParams();if(statusFilter.value)qs.set('status',statusFilter.value);if(yearFilter.value)qs.set('year',yearFilter.value);const j=await api('/orders/tracked?'+qs);applyOrders(j.orders||[],j.summary||{})}
function render(){const q=searchOrders.value.toLowerCase();const rows=allOrders.filter(o=>`${o.store} ${o.order_number} ${o.product_summary}`.toLowerCase().includes(q));ordersList.innerHTML=rows.length?rows.map(o=>`<article class="order-card"><div class="order-head"><div><span class="status-pill status-${esc(o.status)}">${esc(o.status)}</span><h3>${esc(o.store).toUpperCase()} · ${esc(o.order_number)}</h3><p>${esc(o.product_summary||'Product details will improve as receipt emails are parsed.')}</p></div><strong>${money(o.total)}</strong></div><div class="order-meta"><div><small>Order date</small><br><b>${o.order_date?new Date(o.order_date).toLocaleDateString():'—'}</b></div><div><small>Tracking</small><br><b>${esc(o.tracking_number||'—')}</b></div><div><small>Credits spent</small><br><b>${money(o.credits_spent)}</b></div><div><small>Last update</small><br><b>${o.last_status_at?new Date(o.last_status_at).toLocaleString():'—'}</b></div></div><div class="order-actions"><a class="btn" target="_blank" href="${API}/orders/receipt/${o.id}?token=${encodeURIComponent(token)}" onclick="event.preventDefault();openReceipt('${o.id}')">View / Print Receipt</a><button class="btn" onclick="editOrder('${o.id}')">Edit</button><button class="btn btn-danger" onclick="deleteOrder('${o.id}')">Delete</button></div></article>`).join(''):'<section class="panel"><p>No tracked orders match this view yet.</p></section>'}
async function openReceipt(id){const r=await fetch(`${API}/orders/receipt/${id}`,{headers:{Authorization:`Bearer ${token}`}});if(!r.ok){alert('Receipt could not be opened');return}const html=await r.text();const w=window.open('','_blank');w.document.open();w.document.write(html);w.document.close();}
async function editOrder(id){const o=allOrders.find(x=>x.id===id);const status=prompt('Status: confirmed, processing, shipped, delivered, canceled, refunded',o.status);if(!status)return;const credits=prompt('Credits spent for this order',o.credits_spent||0);await api('/orders/tracked/'+id,{method:'PATCH',body:JSON.stringify({status,credits_spent:Number(credits||0)})});loadOrders()}
async function deleteOrder(id){if(!confirm('Delete this tracked order and its stored receipt?'))return;await api('/orders/tracked/'+id,{method:'DELETE'});loadOrders()}
scanNow.onclick=async()=>{scanNow.disabled=true;scanMessage.textContent='Scanning connected inboxes. Large first scans can take a few minutes...';try{const j=await api('/orders/scan',{method:'POST'});scanMessage.textContent=`Scan complete: ${j.accounts||0} connected email account${Number(j.accounts||0)===1?'':'s'} checked.`;await bootstrap()}catch(e){scanMessage.textContent=e.message}finally{scanNow.disabled=false}};
if(window.testAycd)testAycd.onclick=async()=>{testAycd.disabled=true;aycdMessage.textContent='Testing AYCD Inbox API…';try{const j=await api('/orders/aycd-test',{method:'POST',body:JSON.stringify({query:'target order'})});aycdMessage.textContent=`AYCD connected. ${j.messages_found||0} sample messages returned.`}catch(e){aycdMessage.textContent=e.message}finally{testAycd.disabled=false}};
if(window.scanAycd)scanAycd.onclick=async()=>{scanAycd.disabled=true;aycdMessage.textContent='Scanning AYCD Inbox for platform order numbers…';try{const j=await api('/orders/aycd-scan',{method:'POST'});aycdMessage.textContent=`AYCD scan complete: ${j.checked||0} messages checked, ${j.matched||0} platform orders updated.`;await bootstrap()}catch(e){aycdMessage.textContent=e.message}finally{scanAycd.disabled=false}};
printYear.onclick=async()=>{const y=yearFilter.value||new Date().getFullYear();const r=await fetch(`${API}/orders/tax-export?year=${y}`,{headers:{Authorization:`Bearer ${token}`}});if(!r.ok){alert('Annual receipt archive could not be opened');return}const html=await r.text();const w=window.open('','_blank');w.document.open();w.document.write(html);w.document.close();};refreshOrders.onclick=bootstrap;statusFilter.onchange=loadOrders;yearFilter.onchange=loadOrders;searchOrders.oninput=render;
initYears();bootstrap().catch(e=>{scanMessage.textContent=e.message;countAll.textContent='0';countActive.textContent='0';countSuccess.textContent='0';countCanceled.textContent='0';successRate.textContent='0%';ordersList.innerHTML='<section class="panel"><p>Unable to load orders.</p></section>'});
